---

- name: Install python dependencies
  become: true
  hosts: all
  roles:
    - geerlingguy.pip

- name: Deploy web
  become: true
  hosts: all
  tasks:
    - name: Build images
      docker_image:
        name: "{{ item }}"
        tag: "{{ item }}"
        build:
          path: /skillcloud-ngsite
          dockerfile: "Dockerfile-{{ item }}"
      loop:
        - site
        - balance
    - name: Apply Docker-compose
      docker_compose:
        project_src: /skillcloud-ngsite
