---
# - name: check sshd config
#   shell: /usr/sbin/sshd -t
#   listen: restart sshd
- name: restart sshd service
  become: true
  systemd:
    name: sshd
    state: restarted
  # failed_when: false
  listen: restart sshd
- name: wait for port
  wait_for:
    port: "{{ ansible_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "25"
  delegate_to: "localhost"
  listen: restart sshd

# from https://github.com/chmduquesne/ansible-iptables-persistent
- name: save iptables v4 rules
  shell: iptables-save > /etc/iptables/rules.v4
  listen: persist iptables
- name: save iptables v6 rules
  shell: ip6tables-save > /etc/iptables/rules.v6
  listen: persist iptables
