---
# tasks file for ufw

- name: Allow ports
  ufw:
    rule: allow 
    proto: tcp
    port: "{{ item }}"
  loop:
    - "80"
    - "8888"
    - "1467"
- name: Enable and reload UFW
  ufw:
    state: enabled
