---
# tasks file for prepare_site

- name: Create directory
  ansible.builtin.file:
    path: /skillcloud-ngsite
    state: directory
    mode: '0755'

- name: Upload needed files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/skillcloud-ngsite/{{ item }}"
    mode: '0644'
  loop:
    - docker-compose.yml
    - Dockerfile-balance
    - Dockerfile-site
    - index.html

- name: Set up vars
  ansible.builtin.set_fact:
    IP_address_project_1: "{{ hostvars['project_1']['ansible_default_ipv4']['address'] }}"
    IP_address_project_2: "{{ hostvars['project_2']['ansible_default_ipv4']['address'] }}"
    IP_address_project_3: "{{ hostvars['project_3']['ansible_default_ipv4']['address'] }}"

- name: Install balance.conf template
  ansible.builtin.template:
    src: balance.conf
    dest: /skillcloud-ngsite/balance.conf
    mode: '0644'
